### ISSUE TITLE
情報提供

### ISSUE THREAD

**Issue by kaede3pic** [fvh-P/assaultlily-rdf#53]
（以下，列名でなくLemonade項目名で記載）
* 速水桂
- 誕生日: 1/23
-- 出典: https://twitter.com/assault_lily/status/1424391906692190209?s=20
- 好きなもの: 酒盗
-- 出典: https://twitter.com/assault_lily/status/1401937274288230402?s=20
- 特技: 料理
-- 出典: https://twitter.com/assault_lily/status/1414966313743654916?s=20
- ポジション: AZ（セントラルAZ）
-- TZになるのはゼロトップ時（ノインヴェルト時）のみ
-- 可変フォーメーション使用時のポジションは「ポジション」に記載するべき？？？
-- 出典:
--- https://twitter.com/assault_lily/status/1268198802055237633?s=20
--- https://twitter.com/assault_lily/status/1279432724948934656?s=20
--- ↑のスレッド中
- レギオン役職: 司令塔（AZ司令塔）, ゼロトップフィニッシャー
-- 司令塔はレギオンに必ずしも１人とは限らず，かつ「～もこなす」のように固定でもないため単に「司令塔」という記載は誤解を招くのでは？？？
-- 出典:
--- https://twitter.com/assault_lily/status/1249720359252676610?s=20
--- 竹久央ドールリーフレット
- 関連する人物:
-- 山下絢子（私立百合ヶ丘女学院/親友/殉職者・故人）
--- 出典: https://twitter.com/assault_lily/status/1317119038888103937?s=20
-- 竹久央
--- 桂が堅物すぎるのであまり日常生活では馴染んでいないが，薺が桂にあこがれている節があるため央は嫉妬心を隠さない。
--- まとめると「ライバル視」
--- https://twitter.com/assault_lily/status/1268198802055237633?s=20
--- 出典: 竹久央ドールリーフレット
-- 天津麻嶺（御台場迎撃戦/ユニーク機クラウ・ソラスの可変機構を設計）
--- 出典:
--- https://twitter.com/assault_lily/status/1380546812289765376?s=20
--- https://twitter.com/assault_lily/status/1435249968055341061?s=20
--- https://twitter.com/assault_lily/status/1288854575990988800?s=20

**Comment by kaede3pic** [comment]
* 竹久 央
- 「輝ける者たち」は異名ではない。
- 央さんの異名は 「屠竜戦姫」。「ロイヤルエレガンス」は戦場での優雅な「動き」。
- リーフレット情報をどこまで載せられるかよくわからないが，スノーフレークや狂乱の天使も載ってるので指摘。

**Comment by kaede3pic** [comment]
* 田中壱
- https://twitter.com/assault_lily/status/1455556205737168904?s=20
- ↑では「お壱の方やお壱様は百合ヶ丘でのあだ名」と記載されたが，
- https://twitter.com/assault_lily/status/1226180451754135552?s=20
- ↑少なくともここでは「異名」と言っているため，DB上で「あだ名」と「二つ名・異名」の扱いをどうするのかは問題かと。おそらく切り分けができないラインが存在する。
-- 遊糸センパイの異名が（自称）な時点ですでにアレだが。

**Comment by fvh-P** [comment]
提供いただきました情報を基にデータを更新しました。
なお、扱いが微妙な項目の掲載基準はこちらで判断させていただきました。

今回は情報提供ありがとうございました。

変更履歴: be9a96cc3e714fe87429fac54a8bfea9ea079ee1...37e59fe8b773aa4dd436f76ca341a1fd5b3551c8
