### ISSUE TITLE
ライブイベントのセットリストが欲しい

### ISSUE THREAD

**Issue by fvh-P** [fvh-P/assaultlily-rdf#67]
`lily:Concert` クラスでも用意してライブのデータを作りたい
そのために以下各公演、両部のセットリストが欲しい
- Edel Lilie
- Edel Lilie+
- LIVE in TACHIKAWA GARDEN
- (Idol Lily Stage)

**Comment by mintcc342g** [comment]
Edel Lilie Set List
- https://prtimes.jp/main/html/rd/p/000004065.000014827.html

Edel Lilie+ Set List
- https://prtimes.jp/main/html/rd/p/000004502.000014827.html

LIVE in TACHIKAWA GARDEN
- https://prtimes.jp/main/html/rd/p/000004982.000014827.html

「Idol Lily Stage」も多分書かれるかと。
